# Generated by Django 5.1.4 on 2024-12-21 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleTypeMkcModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModuleTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NameAsuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NumberCabinetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NumberCannelMkcModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NumberCannelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NumberModuleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_def', models.DateField(null=True, verbose_name='Дата неисправности')),
                ('channel_purpose', models.CharField(max_length=255, verbose_name='Назначение канала')),
                ('fault', models.CharField(max_length=255, verbose_name='Неисправность')),
                ('author_def', models.CharField(max_length=255, verbose_name='Автор записи')),
                ('events', models.CharField(max_length=255, verbose_name='Мероприятия')),
                ('date_events', models.DateField(null=True, verbose_name='Дата мероприятия')),
                ('author_events', models.CharField(max_length=255, verbose_name='Автор мероприятий')),
                ('module_type_mkc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects.moduletypemkcmodel', verbose_name='Тип модуля МКС')),
                ('module_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects.moduletypemodel', verbose_name='Тип модуля')),
                ('name_asu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects.nameasumodel', verbose_name='Наименование АСУ ТП')),
                ('number_cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects.numbercabinetmodel', verbose_name='№ шкафа')),
                ('number_cannel_mkc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects.numbercannelmkcmodel', verbose_name='№ канала МКС')),
                ('number_cannel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects.numbercannelmodel', verbose_name='№ канала')),
                ('number_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects.numbermodulemodel', verbose_name='№ модуля')),
            ],
            options={
                'ordering': ['-date_events'],
            },
        ),
    ]
