# Generated by Django 5.1.4 on 2025-02-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='author_events_two',
            field=models.CharField(default=12345, max_length=255, verbose_name='Автор мероприятий-2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='date_events_two',
            field=models.DateField(null=True, verbose_name='Дата мероприятия-2'),
        ),
        migrations.AddField(
            model_name='journal',
            name='events_two',
            field=models.CharField(default=12345, max_length=255, verbose_name='Мероприятия-2'),
            preserve_default=False,
        ),
    ]
