# Generated by Django 5.1.4 on 2025-02-04 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0002_journal_author_events_two_journal_date_events_two_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='module_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects.moduletypemodel', verbose_name='Тип модуля УСО'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='number_cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects.numbercabinetmodel', verbose_name='№ шкафа ПТК'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='number_cannel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects.numbercannelmodel', verbose_name='№ канала УСО'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='number_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects.numbermodulemodel', verbose_name='№ модуля УСО'),
        ),
        migrations.AlterField(
            model_name='numbercabinetmodel',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='numbercabinetmodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='numbercannelmkcmodel',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='numbercannelmkcmodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='numbercannelmodel',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='numbercannelmodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='numbermodulemodel',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='numbermodulemodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
