# Generated by Django 5.1.4 on 2025-02-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0003_alter_journal_module_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='number_module_mkc',
            field=models.CharField(default=12345, max_length=255, verbose_name='№ модуля МКС'),
            preserve_default=False,
        ),
    ]
